services:
- type: web
  name: Linebot_Restr
  env: python
  repo: https://github.com/CharlieAlex/Linebot_Restr
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn main:app
  plan: free
  autoDeploy: false
  envVars:
  - key: CHANNEL_ACCESS_TOKEN
    sync: false
  - key: CHANNEL_SECRET
    sync: false
  - key: TZ
    sync: false